apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/PES/sem6/CC/Project-5-20240325T050606Z-001/Project-5/Archive/backup"